sudo: false

language: node_js

node_js:
  - 8 # Active
  - 10
  - 12

notifications:
  email:
    # Only send notifications when travis status changes
    on_failure: never
    on_success: never

cache: npm

branches:
  only:
    - master
    - next

script:
  - npm run lint
  # - firebase setup:emulators:firestore
  # - npm run test:full

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      node: '10'
      branch: 'master'
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: next
    on:
      node: '10'
      branch: 'next'
