name: NPM Package Publish

on:
  push:
    branches:
      - master
      - next

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Get Library Versions For Binary Caching
        id: dep-versions
        run: |
          echo "::set-output name=firebase-tools::$(yarn info firebase-tools version --silent)"

      - name: Cache Firebase Emulator Binaries
        uses: actions/cache@v1
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-${{ steps.dep-versions.outputs.firebase-tools }}

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Check Lint
        run: yarn lint

      - name: Run Unit Tests
        run: yarn test

      - name: Archive Firestore Emulator Debug Log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firestore-debug
          path: firestore-debug.log

      - name: Archive RTDB Emulator Debug Log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: rtdb-debug
          path: database-debug.log

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: npm publish $([ "$GITHUB_REF" == 'refs/heads/next' ] && echo '--tag next')

      # - name: Semantic Release
      #   id: semantic
      #   uses: cycjimmy/semantic-release-action@v2
      #   with:
      #     semantic_version: ^17.0.4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Archive Workspace on Failure
        if: failure()
        run: zip -r workspace-files ./
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: workspace
          path: workspace-files.zip