name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # Setup dependency caching
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile

      - name: Check Lint
        run: yarn lint

      - name: Run Unit Tests
        run: yarn test

      - name: Archive Firestore Emulator Debug Log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firestore-debug
          path: firestore-debug.log

      - name: Archive RTDB Emulator Debug Log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: rtdb-debug
          path: database-debug.log

      - name: Run Build
        run: yarn build