name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # Setup dependency caching
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Get Library Versions For Binary Caching
        id: dep-versions
        run: |
          echo "::set-output name=firebase-tools::$(yarn info firebase-tools version --silent)"

      - name: Cache Firebase Emulator Binaries
        uses: actions/cache@v1
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-${{ steps.dep-versions.outputs.firebase-tools }}

      - name: Install Dependencies
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile

      - name: Check Lint
        run: yarn lint

      - name: Run Unit Tests
        run: yarn test

      - name: Archive Firestore Emulator Debug Log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firestore-debug
          path: firestore-debug.log

      - name: Archive RTDB Emulator Debug Log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: rtdb-debug
          path: database-debug.log

      - name: Run Build
        run: yarn build